# IF ANY CHANGES ARE MADE TO THIS FILE THE DOCKER CONTAINER ON DOCKERHUB MUST ALSO BE UPDATED WITH THE NEW BUILD!

# USE ALPINE LINUX O/S AS BASE IMAGE

FROM alpine:3.20.0

# INSTALL NODE.JS AND ESLINT

RUN apk add --no-cache nodejs=20.13.1-r0 npm=10.8.0-r0 && \
    npm install eslint@9.3.0 -g

# SET THE WORKING DIRECTORY FOR THE CONTAINER

WORKDIR /app

# INCLUDE 'eslint.config.mjs' IN DOCKER BUILD

COPY eslint.config.mjs ./eslint.config.mjs
