name: ESLint                                              # Define the name of the workflow

on: [push, pull_request]                                  # Trigger the workflow on push and pull request events

jobs:                                                     # Define list of jobs
  lint:                                                   # Define a job named 'lint'
    runs-on: ubuntu-latest                                # Specify the type of virtual machine to use (Ubuntu latest version)

    container:                                            # Set container image
      image: monkeyknuckles/eslint                        # Use a Docker container with the eslint image

    steps:                                                # List of steps to execute in the job
      - name: Checkout code                               # Step name: Checkout code from the repository
        uses: actions/checkout@v3                         # Use the checkout action to clone the repository

      - name: Copy eslint config                          # Step name: Copy eslint configuration file
        run: cp /app/eslint.config.mjs $GITHUB_WORKSPACE  # Copy the eslint.config.mjs file from the container to the workspace

      - name: Run markdownlint-cli2                       # Step name: Run eslint
        run: eslint .                                     # Execute the eslint command on all JavaScript files in the repository