name: ESLint                                              # Define the name of the workflow

on: [push, pull_request]                                  # Trigger the workflow on push and pull request events

jobs:                                                     # Initialise job
  lint:                                                   # Define a job named 'lint'
    runs-on: ubuntu-latest                                # Specifies the type of VM to provision

    container:                                            # Set container image
      image: monkeyknuckles/eslint                        # Points to ESLint container

    steps:                                                # List of steps to execute
      - name: Checkout code                               # Checkout code label text
        uses: actions/checkout@v3                         # Use the checkout action to clone the repository

      - name: Copy eslint config                          # Copy ESLint configuration file label text
        run: cp /app/eslint.config.mjs $GITHUB_WORKSPACE  # Include the ESLint configuration file in the docker build

      - name: Run Lint ESLint                             # Set lint ESLint label text
        run: eslint --color .                             # Lint all JavaScript files